//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAB.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] AlignPlanCornerMarksCommand_16 {
            get {
                object obj = ResourceManager.GetObject("AlignPlanCornerMarksCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] AlignPlanCornerMarksCommand_32 {
            get {
                object obj = ResourceManager.GetObject("AlignPlanCornerMarksCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] CreateInteriorElevationsCommand_16 {
            get {
                object obj = ResourceManager.GetObject("CreateInteriorElevationsCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] CreateInteriorElevationsCommand_32 {
            get {
                object obj = ResourceManager.GetObject("CreateInteriorElevationsCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] CreateViewsAndSheets_16 {
            get {
                object obj = ResourceManager.GetObject("CreateViewsAndSheets_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] CreateViewsAndSheets_32 {
            get {
                object obj = ResourceManager.GetObject("CreateViewsAndSheets_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DeleteSelectedTypesAndFamiliesCommand_16 {
            get {
                object obj = ResourceManager.GetObject("DeleteSelectedTypesAndFamiliesCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DeleteSelectedTypesAndFamiliesCommand_32 {
            get {
                object obj = ResourceManager.GetObject("DeleteSelectedTypesAndFamiliesCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DeleteViewsAndSheets_16 {
            get {
                object obj = ResourceManager.GetObject("DeleteViewsAndSheets_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DeleteViewsAndSheets_32 {
            get {
                object obj = ResourceManager.GetObject("DeleteViewsAndSheets_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportLineAndFillPatternsCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ExportLineAndFillPatternsCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportLineAndFillPatternsCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ExportLineAndFillPatternsCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportLoadableFamilyThumbnailsCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ExportLoadableFamilyThumbnailsCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportLoadableFamilyThumbnailsCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ExportLoadableFamilyThumbnailsCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportMaterialNamingCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ExportMaterialNamingCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportMaterialNamingCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ExportMaterialNamingCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportSystemFamilyThumbnailTemplateCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ExportSystemFamilyThumbnailTemplateCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportSystemFamilyThumbnailTemplateCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ExportSystemFamilyThumbnailTemplateCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportTypeNamingCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ExportTypeNamingCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportTypeNamingCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ExportTypeNamingCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportTypesByCategoryCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ExportTypesByCategoryCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportTypesByCategoryCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ExportTypesByCategoryCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportTypesSingleFileCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ExportTypesSingleFileCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ExportTypesSingleFileCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ExportTypesSingleFileCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] FlipElevation180ByLineCommand_16 {
            get {
                object obj = ResourceManager.GetObject("FlipElevation180ByLineCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] FlipElevation180ByLineCommand_32 {
            get {
                object obj = ResourceManager.GetObject("FlipElevation180ByLineCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] GenerateDashboardCommand_16 {
            get {
                object obj = ResourceManager.GetObject("GenerateDashboardCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] GenerateDashboardCommand_32 {
            get {
                object obj = ResourceManager.GetObject("GenerateDashboardCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportByBoundaryCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ImportByBoundaryCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportByBoundaryCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ImportByBoundaryCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportByLineCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ImportByLineCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportByLineCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ImportByLineCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportByPointCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ImportByPointCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportByPointCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ImportByPointCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportMaterialNamingCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ImportMaterialNamingCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportMaterialNamingCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ImportMaterialNamingCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportTypeNamingCommand_16 {
            get {
                object obj = ResourceManager.GetObject("ImportTypeNamingCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ImportTypeNamingCommand_32 {
            get {
                object obj = ResourceManager.GetObject("ImportTypeNamingCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] LoadSystemFamilyTypeImagesCommand_16 {
            get {
                object obj = ResourceManager.GetObject("LoadSystemFamilyTypeImagesCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] LoadSystemFamilyTypeImagesCommand_32 {
            get {
                object obj = ResourceManager.GetObject("LoadSystemFamilyTypeImagesCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] MoveElevationViewportsToNewSheetCommand_16 {
            get {
                object obj = ResourceManager.GetObject("MoveElevationViewportsToNewSheetCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] MoveElevationViewportsToNewSheetCommand_32 {
            get {
                object obj = ResourceManager.GetObject("MoveElevationViewportsToNewSheetCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] OpenNamingStandardsHtmlCommand_16 {
            get {
                object obj = ResourceManager.GetObject("OpenNamingStandardsHtmlCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] OpenNamingStandardsHtmlCommand_32 {
            get {
                object obj = ResourceManager.GetObject("OpenNamingStandardsHtmlCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] OpenPluginInstructionsHtmlCommand_16 {
            get {
                object obj = ResourceManager.GetObject("OpenPluginInstructionsHtmlCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] OpenPluginInstructionsHtmlCommand_32 {
            get {
                object obj = ResourceManager.GetObject("OpenPluginInstructionsHtmlCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] PlaceFillPatternsCommand_16 {
            get {
                object obj = ResourceManager.GetObject("PlaceFillPatternsCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] PlaceFillPatternsCommand_32 {
            get {
                object obj = ResourceManager.GetObject("PlaceFillPatternsCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] PlaceLineStylesCommand_16 {
            get {
                object obj = ResourceManager.GetObject("PlaceLineStylesCommand_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] PlaceLineStylesCommand_32 {
            get {
                object obj = ResourceManager.GetObject("PlaceLineStylesCommand_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SyncReminderSettings_16 {
            get {
                object obj = ResourceManager.GetObject("SyncReminderSettings_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SyncReminderSettings_32 {
            get {
                object obj = ResourceManager.GetObject("SyncReminderSettings_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
